petadopter/accounts/urls.py
from django.urls import path, include
from . import views  # '.' because in same folder

app_name = 'accounts'

urlpatterns = [
    path('', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

petadopter/adopter/urls.py
from . import views
from django.urls import path, include

app_name = 'adopter'

urlpatterns = [
    path('', views.PostList, name='list'),
    path('create/', views.PostCreate, name='create'),
    path('<slug:slug>/', views.PostDetail, name='detail'),
]

petadopter/petadopter/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('base/', views.base),
    path('adopter/', include('adopter.urls'), name='adopter'),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petadopter/accounts/models.py
from django.db import models

# Create your models here.

petadopter/adopter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    #status = models.IntegerField(choices=STATUS, default=0)
    thumb = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.content[:50]

petadopter/adopter/forms.py
from django import forms
from . import models

# Create your views here.


class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'slug', 'author',
                  'content', 'thumb']

petadopter/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('adopter:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('adopter:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('adopter:list')

petadopter/adopter/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import Post
from . import forms
from django.contrib.auth.decorators import login_required


# Create your views here.


def PostList(request):
    posts = Post.objects.all().order_by('updated_on')
    # return render(request,'recipes/recipe_list.html',{'recipes':recipes})
    return render(request, 'adopter/post_list.html', {'posts': posts})


def PostDetail(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'adopter/post_detail.html', {'post': post})


def PostCreate(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        # create a form instance and populate it with data from the request:
        if form.is_valid():
            # process data and return to exercise list
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('adopter:list')
    else:
        form = forms.CreatePost()
        return render(request, 'adopter/post_create.html', {'form': form})

petadopter/petadopter/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    # return HttpResponse('homepage')
    return render(request, 'home.html')


def base(request):
    # return HttpResponse('homepage')
    return render(request, 'base.html')

petadopter/accounts/templates/accounts/login.html
{% extends 'base.html'%} {% block content %}
<h1 class="big">Enter for the good stuff!</h1>
<h3>Login!</h3>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
  {% csrf_token %} {{ form }} {% if request.GET.next %}
  <input type="hidden" name="next" value="{{ request.GET.next }}" />
  {% endif %}
  <input type="submit" value="Login" />
</form>
<form class="signup" action="{% url 'accounts:signup' %}">
  <button type="submit">Signup!</button>
</form>

{% endblock %}

petadopter/accounts/templates/accounts/signup.html
{% extends 'base.html'%} {% block content %}
<h1 class="big">Join the crew now!</h1>
<h3>Sign Up Here!</h3>
<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
  {% csrf_token %} {{ form }}
  <input type="submit" value="Signup" />
</form>
{% endblock %}

petadopter/adopter/templates/adopter/post_create.html
{% extends 'base.html' %} {% block content %}
<div class="create-post">
  <h2>Create a new adoption post!</h2>
  <form
    class="site-form"
    action="{% url 'adopter:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {% csrf_token %} {{ form }}
    <input type="submit" value="Create" />
  </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

petadopter/adopter/templates/adopter/post_detail.html
{% extends 'base.html'%} {% block content %}
<div class="post-detail">
  <div class="post">
    <img src="{{post.thumb.url}}" width="200" height="auto" />
    <h1>{{post.title}}</h1>
    <p>{{post.content}}</p>
  </div>
</div>

{% endblock %}

petadopter/adopter/templates/adopter/post_list.html
{% extends 'base.html'%} {% block content %}

<h1>Up for adoption</h1>
<div class="posts">
  {% for post in posts %}
  <div class="post">
    <h2>
      <a href="{% url 'adopter:detail' slug=post.slug %}">{{post.title}}</a>
    </h2>
  </div>
  {% endfor %}
</div>

{% endblock %}

petadopter/templates/base.html
{% load static from static%}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Pet Adopter</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
  </head>
  <body>
    <div class="navbar">
      <a href="{% url 'adopter:list' %}"
        ><img src="{% static 'logo.png' %}"
      /></a>
      <div class="dropdown">
        <button class="dropbtn">Index</button>
        <div class="dropdown-content">
          <a href="{% url 'adopter:list' %}" class="highlight">Adoption List</a>
          <a href="{% url 'adopter:create' %}" class="highlight"
            >Submit your rescue Here!</a
          >
        </div>
      </div>

      <div class="login-container">
        {% if user.is_authenticated %}
        <form
          class="logout-link"
          action="{% url 'accounts:logout' %}"
          method="post"
        >
          {% csrf_token %}
          <button type="submit">Logout</button>
        </form>

        {% else %}
        <div class="logsign">
          <form class="login-link" action="{% url 'accounts:signup' %}">
            <button type="submit">Signup!</button>
          </form>
        </div>
        <div class="logsign">
          <form
            class="login-link"
            action="{% url 'accounts:login' %}"
            method="post"
          >
            {% csrf_token %}
            <button type="submit">Login</button>
          </form>
        </div>
        {% endif %}
      </div>
    </div>
    <!-- <div class="logo">
      <h1>
        <a href="{% url 'adopter:list' %}"
          ><img src="{% static 'logo.png' %}"
        /></a>
      </h1>
    </div> -->
    <div class="wrapper">{% block content %} {% endblock %}</div>
  </body>
</html>

petadopter/templates/home.html
{% extends 'base.html'%}
{% block content %}
    <h1>Welcome to Pet Adopter!</h1>
    <p>Find your new best friend here!</p>
  </body>
</html>
{% endblock %}